security:
  user:
    name: root
    password: 1234
  oauth2:
    resource:
    filter-order: 3

server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG


#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=yes&characterEncoding=UTF-8
#    username: root
#    password: 123456
